Repository SwaveReleaseNote/FrontEnd-template, pull requests merged in 2023-08, with the labels that each got.

#27 Create testtest.md
  testtest.md
Labels: docs, test

#38 34-feature-degisn-change
  src/components/navbar/index.tsx
  src/views/admin/default/components/MemberStatusCard.tsx
  src/views/admin/default/components/PieChartCard2.tsx
  src/views/admin/default/components/ProjectCard.tsx
  src/views/admin/default/components/SearchReleaseList.tsx
  src/views/admin/default/index.tsx
  src/views/admin/default/pages/CreateProject.tsx
  src/views/admin/default/pages/ManageProject.tsx
  src/views/admin/default/pages/SearchProjectList.tsx
Labels: fix, design

#44 리액트 쿼리 적용 및 프로젝트 구독하기 백엔드 연동 확인
  src/dist/routes.js
  src/index.tsx
  src/routes.tsx
  src/views/admin/default/MainPage.tsx
  src/views/admin/default/components/CheckboxLabel.tsx
  src/views/admin/default/components/MemberStatusCard.tsx
  src/views/admin/default/components/NotificationPopup.tsx
  src/views/admin/default/components/PieChartCard2.tsx
  src/views/admin/default/components/ProjectCard.tsx
  src/views/admin/default/components/RecentCommentList.tsx
  src/views/admin/default/components/RecentRelease.tsx
  src/views/admin/default/components/SearchReleaseList.tsx
  src/views/admin/default/components/scrollbar.css
  src/views/admin/default/pages/CreateProject.tsx
  src/views/admin/default/pages/ManageProject.tsx
  src/views/admin/default/pages/ProjectDashboard.tsx
  src/views/admin/default/pages/SearchProjectList.tsx
  src/views/auth/SignIn.tsx
  src/views/auth/UserProfileCard.tsx
Labels: feat, fix

#53 45 Response Status에 따른 에러 처리 & 해상도에 따라 다르게 보이는 컴포넌트 디자인 수정
  .eslintrc.json
  src/assets/img/error/400.jpg
  src/assets/img/error/401.png
  src/assets/img/error/404.jpg
  src/assets/img/error/500.jpg
  src/components/charts/PieChart2.tsx
  src/components/navbar/index.tsx
  src/components/sidebar/index.tsx
  src/error/Error.tsx
  src/layouts/admin/index.tsx
  src/routes.tsx
  src/sideBarRoutes.tsx
  src/views/admin/default/MainPage.tsx
  src/views/admin/default/components/MemberStatusCard.tsx
  src/views/admin/default/components/PieChartCard2.tsx
  src/views/admin/default/components/ProjectCard.tsx
  src/views/admin/default/components/RecentCommentList.tsx
  src/views/admin/default/components/RecentRelease.tsx
  src/views/admin/default/components/SearchReleaseList.tsx
  src/views/admin/default/pages/CreateProject.tsx
  src/views/admin/default/pages/ManageProject.tsx
  src/views/admin/default/pages/ProjectDashboard.tsx
  src/views/admin/default/pages/SearchProjectList.tsx
  src/views/auth/Auth.tsx
  src/views/auth/Logout.tsx
  src/views/auth/SignIn.tsx
  src/views/auth/UserProfileCard.tsx
Labels: bugfix, feat, design
